### ISSUE TITLE
ALL_PAGES button doesn't marked

### ISSUE THREAD

**Issue by githubjeka** [bupy7/yii2-grid#5]
![image](https://user-images.githubusercontent.com/874234/26928121-7566d0a2-4c5d-11e7-8a89-888e179bf790.png)

**Comment by bupy7** [comment]
Need set page range ($pageSizeLimit) in `yii\data\Pagination`. By default `[1, 50]`.

**Comment by githubjeka** [comment]
https://github.com/bupy7/yii2-grid#adding-ability-display-all-rows-of-grid

**Comment by bupy7** [comment]
There is don't wrote, you right.

**Comment by bupy7** [comment]
Added description in readme.
